name       : haskell-adjunctions
version    : 4.3
release    : 1
source     :
    - https://hackage.haskell.org/package/adjunctions-4.3/adjunctions-4.3.tar.gz : b948a14fafe8857f451ae3e474f5264c907b5a2d841d52bf78249ae4749c3ecc
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides adjunctions for Haskell.
description: |
    This package provides adjunctions for Haskell.
builddeps  :
    - haskell-cabal-install
    - haskell-free
    - haskell-profunctors
    - haskell-semigroupoids
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
