name       : haskell-adjunctions
version    : '4.4'
release    : 2
source     :
    - http://hackage.haskell.org/package/adjunctions-4.4/adjunctions-4.4.tar.gz : 507c2ef55337ae61c805f8cbc1213dfd7d2b85187342675d662254b8d8a16ae9
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides adjunctions for Haskell.
description: |
    This package provides adjunctions for Haskell.
builddeps  :
    - haskell-cabal-install
    - haskell-free
    - haskell-profunctors
    - haskell-semigroupoids
    - haskell-void
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
